logs:
  min_size: 200000  # kb
upload:
  url: https://dps.report/
  backup: https://b.dps.report/
  endpoint: uploadContent?json=1
  user_token: &token glennaUploader
  params: { "json": "1", "userToken": *token }
  rate_limit: 25
  rate_timeout_seconds: 60
  backoff_factor: 0.2
  retries: 8
  parallel_connections: 6
raids:
  en:
    - Vale Guardian (15438)
    - Gorseval the Multifarious (15429)
    - Sabetha the Saboteur (15375)
    - Slothasor (16123)
    - Berg (16088)
    - Matthias Gabrel (16115)
    - McLeod the Silent (16253)
    - Keep Construct (16235)
    - Haunting Statue (16247)
    - Xera (16246)
    - Cairn the Indomitable (17194)
    - Mursaat Overseer (17172)
    - Samarog (17188)
    - Deimos (17154)
    - Soulless Horror (19767)
    - Desmina (19828)
    - Broken King (19691)
    - Eater of Souls (19536)
    - Eye of Judgment (19651)
    - Eye of Fate (19844)
    - Dhuum (19450)
    - Conjured Amalgamate (43974)
    - Nikare (21105)
    - Qadim (20934)
    - Cardinal Adina (22006)
    - Cardinal Sabir (21964)
    - Qadim the Peerless (22000)
    - Greer, the Blightbringer (26725)
    - Decima, the Stormsinger (26774)
    - Ura (26712)
  de:
    - Tal-Wächter (15438)
    - Gorseval der Facettenreiche (15429)
    - Sabetha die Saboteurin (15375)
    - Faultierion (16123)
    - Berg (16088)
    - McLeod der Stille (16253)
    - Matthias Gabrel (16115)
    - Festenkonstrukt (16235)
    - Spukende Statue (16247)
    - Xera (16246)
    - Cairn der Unbeugsame (17194)
    - Mursaat-Aufseher (17172)
    - Samarog (17188)
    - Deimos (17154)
    - Seelenloser Schrecken (19767)
    - Desmina (19828)
    - Bezwungener König (19691)
    - Seelenverzehrer (19536)
    - Auge des Urteils (19651)
    - Auge des Schicksals (19844)
    - Dhuum (19450)
    - Beschworene Verschmelzung (43974)
    - Nikare (21105)
    - Qadim (20934)
    - Kardinal Adina (22006)
    - Kardinal Sabir (21964)
    - Qadim der Unvergleichliche (22000)
    - Greer, der Pestilenzbringer (26725)
    - Decima, die Sturmsängerin (26774)
    - Ura (26712)
strikes:
  en:
    - Icebrood Construct (22154)  # Missing cause didn't run and probably won't that quickly
    - Voice of the Fallen (22343)
    - Claw of the Fallen (22481)
    - Fraenir of Jormag (22492)
    - Boneskinner (22521)
    - Whisper of Jormag (22711)
    - Freezie (21333)
    - Captain Mai Trin (24033)
    - Ankka (23957)
    - Minister Li (24266)
    - The Dragonvoid (43488)
    - Prototype Vermilion (25413)  # Normal Mode
    - Prototype Vermilion (25414)  # CM
    - Dagda (25705)
    - Cerus (25989)
  de:
    - Eisbrut-Konstrukt (22154)
    - Stimme der Gefallenen (22343)
    - Klaue der Gefallen (22481)
    - Fraenir Jormags (22492)
    - Knochenhäuter (22521)
    - Geflüster des Jormag (22711)
    - Frostie (21333)
    - Kapitän Mai Trin (24033)
    - Ankka (23957)
    - Minister Li (24266)
    - Die Drachenleere (24375)
    - Prototyp Vermillion (25413)  # Normal Mode
    - Prototyp Vermillion (25414)  # CM
    - Dagda (25705)
    - Cerus (25989)
fractals:
  en:
    - MAMA (17021)
    - Siax the Corrupted (17028)
    - Ensolyss of the Endless Torment (16948)
    - Skorvald the Shattered (17632)
    - Artsariiv (17949)
    - Arkk (17759)
    - Sorrowful Spellcaster (17759)  # Name guessed
    - Kanaxai, Scythe of House Aurkus (25577)
    - Eparch (26231)  # Translation guessed
  de: # Thanks, Grisu!
    - MAMA (17021)
    - Albtraum-Oratuss (17028)
    - Ensolyss der endlosen Pein (16948)
    - Skorvald der Zerschmetterte (17632)
    - Artsariiv (17949)
    - Arkk (17759)
    - Gramvolle Zauberwirkerin (23254)
    - Kanaxai, Sense des Hauses Aurkus (25577)
    - Eparch (26231)
