logs:
  min_size: 200000  # kb
upload:
  url: https://dps.report/uploadContent?json=1
  backup: https://b.dps.report/uploadContent?json=1
  endpoint: uploadContent?json=1  # TODO: Use this or remove
  params: {"json": "1"}  # TODO: Use this or remove
  rate_limit: 25  # TODO: Use this or remove
  rate_timeout_seconds: 60  # TODO: Use this or remove
  backoff_factor: 0.2  # TODO: Use this or remove
  retries: 8
  parallel_connections: 6
  user_token: userToken=2er3ubphpf732libpkedhui572krbj4i  # TODO: Use the token
raids:  # TODO: Get all the new folder names: boss (id)
  en:
    - Vale Guardian
    - Gorseval the Multifarious
    - Sabetha the Saboteur
    - Slothasor
    - Berg
    - Matthias Gabrel
    - Keep Construct
    - Haunting Statue
    - Xera
    - Cairn the Indomitable
    - Mursaat Overseer
    - Samarog
    - Deimos
    - Soulless Horror
    - Broken King
    - Eater of Souls
    - Eye of Judgment
    - Eye of Fate
    - Dhuum
    - Conjured Amalgamate
    - Nikare
    - Qadim
    - Cardinal Adina
    - Cardinal Sabir
    - Qadim the Peerless
  de:
    - Tal-Wächter
    - Gorseval der Facettenreiche
    - Sabetha die Saboteurin
    - Faultierion
    - Berg
    - Matthias Gabrel
    - Festenkonstrukt
    - Spukende Statue
    - Xera
    - Cairn der Unbeugsame
    - Mursaat-Aufseher
    - Samarog
    - Deimos
    - Seelenloser Schrecken
    - Desmina
    - Bezwungener König
    - Seelenverzehrer
    - Auge des Urteils
    - Auge des Schicksals
    - Dhuum
    - Beschworene Verschmelzung
    - Nikare
    - Qadim
    - Kardinal Adina
    - Kardinal Sabir
    - Qadim der Unvergleichliche
strikes:
  en:
    - Icebrood Construct
    - Voice of the Fallen
    - Fraenir of Jormag
    - Boneskinner
    - Whisper of Jormag
    - Freezie
    - Captain Mai Trin
    - Ankka
    - Minister Li
    - The Dragonvoid
    - Prototype Vermilion
    - Dagda
    - Cerus
  de:
    - Eisbrut-Konstrukt
    - Stimme der Gefallenen
    - Fraenir Jormags
    - Knochenhäuter
    - Stimme der Gefallenen
    - Kapitän Mai Trin
    - Ankka
    - Minister Li
    - Die Drachenleere
    - Prototyp Vermillion
fractals:
  en:
    - Siax the Corrupted
    - Ensolyss of the Endless Torment
    - Skorvald the Shattered
    - Artsariiv
    - Arkk
    # missing: newer than arkk
  de:
    - MAMA
    - Albtraum-Oratuss
    - Ensolyss der endlosen Pein
    - Skorvald der Zerschmetterte
    # missing: artsariiv, arkk, newer than arkk